name: Build Docker Image
on:
  push:
    tags:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set env
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t ${{secrets.DOCKER_USERNAME}}/cp-app:${{ env.RELEASE_VERSION }}
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKER_USERNAME}}/cd-app:${{ env.RELEASE_VERSION }}